# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 309)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setStyleSheet("#title {\n"
"    background-color:grey;\n"
"    color: white;\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.enumerate = QtWidgets.QLabel(self.centralwidget)
        self.enumerate.setGeometry(QtCore.QRect(390, 250, 81, 41))
        self.enumerate.setAlignment(QtCore.Qt.AlignCenter)
        self.enumerate.setObjectName("enumerate")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(230, 260, 141, 21))
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton.setObjectName("nextButton")
        self.stashButton = QtWidgets.QPushButton(self.centralwidget)
        self.stashButton.setGeometry(QtCore.QRect(60, 260, 141, 21))
        self.stashButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stashButton.setObjectName("stashButton")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(20, 60, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.fromLabel = QtWidgets.QLabel(self.centralwidget)
        self.fromLabel.setGeometry(QtCore.QRect(20, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fromLabel.setFont(font)
        self.fromLabel.setObjectName("fromLabel")
        self.textLabel = QtWidgets.QLabel(self.centralwidget)
        self.textLabel.setGeometry(QtCore.QRect(20, 160, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel.setFont(font)
        self.textLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.textLabel.setWordWrap(True)
        self.textLabel.setOpenExternalLinks(False)
        self.textLabel.setObjectName("textLabel")
        self.subjectLabel = QtWidgets.QLabel(self.centralwidget)
        self.subjectLabel.setGeometry(QtCore.QRect(20, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subjectLabel.setFont(font)
        self.subjectLabel.setObjectName("subjectLabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 140, 421, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Demo Email reader"))
        self.enumerate.setText(_translate("MainWindow", "1/10"))
        self.nextButton.setText(_translate("MainWindow", "Read Next Email"))
        self.stashButton.setText(_translate("MainWindow", "Stash Email"))
        self.titleLabel.setText(_translate("MainWindow", "Title"))
        self.fromLabel.setText(_translate("MainWindow", "From:"))
        self.textLabel.setText(_translate("MainWindow", "..."))
        self.subjectLabel.setText(_translate("MainWindow", "Subject:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
